#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     C1_1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     C1_2,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     C2_1,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     C2_2,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//OmniKnight

#include "joystickDriver.c"
task main()
{
	int threshold = 20;
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy1Btn(8) == 0)
		{
			if(joy1Btn(5) == 0)
			{
				if(joy1Btn(6) == 0)
				{
					getJoystickSettings(joystick);
					if(abs(joystick.joy1_y1) > threshold)
						{
							motor[C1_2] = joystick.joy1_y1;
							motor[C2_2] = joystick.joy1_y1;
						}
						else
						{
							motor[C1_2] = 0;
							motor[C2_2] = 0;
						}

						//

						if(abs(joystick.joy1_x1) > threshold)
						{
							motor[C1_1] = joystick.joy1_x1;
							motor[C2_1] = joystick.joy1_x1;
						}
						else
						{
							motor[C1_1] = 0;
							motor[C2_1] = 0;
						}
				}
				if(joy1Btn(6) == 1) //R Bumper
					{
						motor[C1_1] = -100;
						motor[C2_1] = 100;
						motor[C1_2] = 100;
						motor[C2_2] = -100;
					}
				}
				if(joy1Btn(5) == 1) //L Bumper
					{
					motor[C1_1] = 100;
					motor[C2_1] = -100;
					motor[C1_2] = -100;
					motor[C2_2] = 100;
				}
			}
			if(joy1Btn(8) == 1)
			{
				StopAllTasks();
			}
		}
	}
