#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     C1_1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     C1_2,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     C2_1,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     C2_2,          tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//OmniKnight

#include "joystickDriver.c"
task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy1Btn(8) == 0)
		{
			if(joy1Btn(5) == 0)
			{
				if(joy1Btn(6) == 0)
				{
					if(joy1Btn(0) == 0)
					{
						getJoystickSettings(joystick);
						float siderate = 0.000048 * pow(joystick.joy1_x1, 3);
						float forwardrate = 0.000048 * pow(joystick.joy1_y1, 3);
						motor[C1_1] = forwardrate;
						motor[C2_1] = forwardrate;
						//
						motor[C1_2] = siderate;
						motor[C2_2] = siderate;
					}
					if(joy1Btn(1) == 1)
					{
						getJoystickSettings(joystick);
						float siderate = 0.000048 * pow(joystick.joy1_x1, 3);
						float forwardrate = 0.000048 * pow(joystick.joy1_y1, 3);
						motor[C1_2] = 0.5 * forwardrate;
						motor[C1_2] = 0.5 * forwardrate;
						//
						motor[C2_1] = 0.5 * siderate;
						motor[C2_2] = 0.5 * siderate;
					}
					if(joy1Btn(6) == 1) //R Bumper
					{
						motor[C1_1] = 100;
						motor[C1_2] = 100;
						motor[C2_1] = 100;
						motor[C2_2] = -100;
					}
				}
				if(joy1Btn(5) == 1) //L Bumper
				{
					motor[C1_1] = 100;
					motor[C1_2] = -100;
					motor[C2_1] = -100;
					motor[C2_2] = 100;
				}
			}
			if(joy1Btn(8) == 1)
			{
				StopAllTasks();
			}
		}
	}
}
