#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     compass,        sensorI2CHiTechnicCompass)
#pragma config(Motor,  mtr_S1_C1_1,     C1_1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     C1_2,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     C2_1,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     C2_2,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//OWL
//OmniWheel Locomotion

#include "joystickDriver.c"
task main()
{
	while(true)
	{
	if(joy1Btn(8) == 0)
		{
			if(joy1Btn(5) == 0)
			{
				if(joy1Btn(6) == 0)
				{
					getJoystickSettings(joystick);
					float siderate = 0.000048 * pow(joystick.joy1_x1, 3);
					float forwardrate = 0.000048 * pow(joystick.joy1_y1, 3);
					motor[C1_2] = forwardrate;
					motor[C2_2] = forwardrate;
					//
					motor[C1_1] = siderate;
					motor[C2_1] = siderate;
				} n
				if(joy1Btn(6) == 1) //R Bumper
				{
					motor[C1_1] = -50;
					motor[C2_1] = 50;
					motor[C1_2] = 50;
					motor[C2_2] = -50;
				}
			}
			if(joy1Btn(5) == 1) //L Bumper
			{
				motor[C1_1] = 50;
				motor[C2_1] = -50;
				motor[C1_2] = -50;
				motor[C2_2] = 50;
			}
		}
		if(joy1Btn(8) == 1)
		{
			StopAllTasks();
		}
	}
}
