#pragma config(Motor,  motorB,          leftmotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightmotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "joystickDriver.c"

task main()
{
	int threshold = 20;
	while(true)
	{
		getJoystickSettings(joystick);
		{
			if(abs(joystick.joy1_y1) > threshold)
			{
				motor[motorB] = joystick.joy1_y1;
			}
			if(abs(joystick.joy1_y1) < threshold)
			{
				motor[motorB] = 0;
			}
			if(abs(joystick.joy1_y2) > threshold)
			{
				motor[motorC] = joystick.joy1_y2;
			}
			else
			{
				motor[motorC] = 0;
				if(joy1Btn(5) == 1)
					{
						motor[motorB] = 100;
						motor[motorC] = -100;
					}
				if(joy1Btn(4) == 1)
					{
						motor[motorB] = -100;
						motor[motorC] = 100;
					}
			}
		}
	}
}
