#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     C1_1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     C1_2,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     C2_1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     C2_2,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "joystickDriver.c"

bool starboard_down;
bool hull_down;
bool port_down;

task main()
{
	while(true)
	{
		//Movement
		if(joy1Btn(5) == 1) //R Bumper
		{
			motor[C1_1] = 100;
			motor[C1_2] = 100;
			motor[C2_1] = 100;
			motor[C2_2] = 100;
		}
		else
		{
			if(joy1Btn(7) == 1) //R Trigger
			{
				motor[C1_1] = 20;
				motor[C1_2] = 20;
				motor[C2_1] = -20;
				motor[C2_2] = -20;
			}
			else
			{
				if(joy1Btn(6) == 1) //L Bumper
				{
					motor[C1_1] = 100;
					motor[C1_2] = 100;
					motor[C2_1] = 100;
					motor[C2_2] = 100;
				}
				else
				{
					if(joy1Btn(8) == 1) //R Trigger
					{
						motor[C1_1] = -20;
						motor[C1_2] = -20;
						motor[C2_1] = 20;
						motor[C2_2] = 20;
					}
					else
					{
						if(joy1Btn(2) == 1)
						{
							getJoystickSettings(joystick);
							float side = 0.000048 * pow(joystick.joy1_x1, 3);
							float forward = 0.000048 * pow(joystick.joy1_y1, 3);
							motor[C1_1] = 0.5 * forward;
							motor[C2_1] = 0.5 * forward;
							//
							motor[C1_2] = 0.5 * side;
							motor[C2_2] = 0.5 * side;
						}
						else
						{
							getJoystickSettings(joystick);
							float side = 0.000048 * pow(joystick.joy1_x1, 3);
							float forward = 0.000048 * pow(joystick.joy1_y1, 3);
							motor[C1_1] = forward;
							motor[C2_1] = forward;
							//
							motor[C1_2] = side;
							motor[C2_2] = side;
						}
					}
				}
			}
		}

		//Starboardside Servos
		if(joy2Btn(3) == 1)
		{
			if(!starboard_down)
			{
				servo[servo1] = 220;
				servo[servo2] = 20;
				starboard_down = true;
				wait10Msec(50);
			}
			else
			{
				servo[servo1] = 30;
				servo[servo2] = 230;
				starboard_down = false;
				wait10Msec(50);
			}
		}

		//Portside Servos
		if(joy2Btn(1) == 1)
		{
			if(!port_down)
			{
				servo[servo3] = 240;
				servo[servo4] = 30;
				port_down = true;
				wait10Msec(50);
			}
			else
			{
				servo[servo3] = 40;
				servo[servo4] = 230;
				port_down = false;
				wait10Msec(50);
			}
		}
	}

}
