#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     red1,           sensorI2CCustom)
#pragma config(Sensor, S3,     red2,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-irseeker-v2.h"  //Include infrared sensor driver

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	////                                                   ////
	////    Add your robot specific autonomous code here.  ////
	////                                                   ////
	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	wait10Msec(1700);
	int lefteye = 0;
	int righteye = 0;

	while(true)
	{
		if(HTIRS2setDSPMode(red1, DSP_1200))
		{
			break;
		}
		wait1Msec(100);
	}
	while(true)
	{
		if(HTIRS2setDSPMode(red2, DSP_1200))
		{
			break;
		}
		wait1Msec(100);
	}

	ClearTimer(T1);
	int startTime = time1[T1];
	motor(mtr_S1_C1_1)=100;
	motor(mtr_S1_C1_2)=50;
	while(true)
	{
		lefteye = HTIRS2readDCDir(red1);
		righteye = HTIRS2readDCDir(red2);
		nxtDisplayTextLine(1,"RightEye: %d", righteye);
		nxtDisplayTextLine(2,"LeftEye: %d", lefteye);
		if ((lefteye == 5) && (righteye == 5))
		{
			break;
		}
	}

	nxtDisplayTextLine(3,"Got it!!");
	wait10Msec(10);
	motor(mtr_S1_C1_1)=0;
	motor(mtr_S1_C1_2)=0;
	wait10Msec(50);
	servo(servo2)=0;
	wait10Msec(50);
	servo(servo2)=100;

	motor(mtr_S1_C1_1)=100;
	motor(mtr_S1_C1_2)=40;
	while((time1[T1] - startTime) < 4500)
	{
	}
	wait10Msec(10);
	motor(mtr_S1_C1_1)=100;
	motor(mtr_S1_C1_2)=0;
	wait10Msec(150);

	motor(mtr_S1_C1_1)=100;
	motor(mtr_S1_C1_2)=50;
	wait10Msec(90);

	motor(mtr_S1_C2_1)=100;
	wait10Msec(50);

	motor(mtr_S1_C2_1)=0;
	motor(mtr_S1_C1_1)=100;
	motor(mtr_S1_C1_2)=0;
	wait10Msec(300);

	motor(mtr_S1_C1_1)=100;
	motor(mtr_S1_C1_2)=50;
	wait10Msec(150);
}
