#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,      ,             tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//TJoystick joystick;

task main()
{
	while (true)
	{
		//drive controls `1

		getJoystickSettings(joystick);
		motor[mtr_S1_C1_1] = 0.0000488 * pow(joystick.joy1_y2, 3);
		motor[mtr_S1_C1_2] = 0.0000488 * pow(joystick.joy1_y1, 3);

		//grip controls

		if(joy2Btn(7) == 1)
		{
			servo[servo1] = 180;	//nom position
		}
		else if(joy2Btn(8) == 1)
		{
			servo[servo1] = 0;	//open position
		}
		if(joy2Btn(2) == 1)
		{
			motor[mtr_S1_C4_2] = -100;
		}
		if(joy2Btn(2) == 0)
		{
			if(joy2Btn(1) == 1)
			{
				motor[mtr_S1_C4_2] = 100;
			}
			else
			{
				motor[mtr_S1_C4_2] = 0;
			}
		}
		if(joy2Btn(3) == 1)
		{
			servo[servo2] = 170;	//nom position
		}
		else if(joy2Btn(4) == 1)
		{
			servo[servo2] = 0;	//open position
		}


		//arm controls

		motor[mtr_S1_C2_1] = 0.0000488 * pow(joystick.joy2_y1, 3);
		motor[mtr_S1_C4_1] = 0.0000488 * pow(joystick.joy2_y2, 3);





	}
}
